name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
  
  
jobs:

  build:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L "https://get.spectralops.io/api/download/get?dsn=$SPECTRAL_DSN" | sudo sh
      - name: Scan
        run: spectral scan
